opt = Initialize();
mesh = Mesh(opt.node_num,...
            opt.element_num,...
            opt.nodes,...
            opt.edge_m_nums,...
            opt.edge_c_nums,...
            opt.node_ms,...
            opt.node_cs,...
            opt.node_m_ids );
load = Load(opt.load_num,opt.load_type,opt.q,opt.node_i,opt.node_j);
dbc = Displacement_BC(opt.dbc_num,opt.dbc_node,opt.dbc_type,opt.d);
vcfem = VCFEM(opt.E_m,opt.E_c,opt.pr_m,opt.pr_c);
Ke = vcfem.assembly_global_stiffness_matrix(mesh);
F = vcfem.calculate_global_nodal_load(mesh,load);
vcfem.displacement_condition(dbc,10^5);
K = vcfem.K;
d_m = vcfem.solve_displacement_external_node();